apiVersion: v1
kind: Service
metadata:
  name: kulturtanken
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    io.kompose.service: kulturtanken
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kulturtanken
  labels:
    io.kompose.service: kulturtanken
spec:
  selector:
    matchLabels:
      io.kompose.service: kulturtanken
  template:
    metadata:
      labels:
        io.kompose.service: kulturtanken
    spec:
      containers:
        - name: kulturtanken-beta
          image: fintlabs.azurecr.io/kulturtanken:build.10
          resources:
            limits:
              memory: "1.5Gi"
              cpu: "500m"
            requests:
              cpu: "100m"
              memory: "256Mi"
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /tjenester/kulturtanken/actuator/health
          env:
            - name: TZ
              value: Europe/Oslo
            - name: spring.security.oauth2.client.registration.971045698.client-id
              valueFrom:
                secretKeyRef:
                  key: client-id
                  name: kulturtanken-rogaland
            - name: spring.security.oauth2.client.registration.971045698.client-secret
              valueFrom:
                secretKeyRef:
                  key: client-secret
                  name: kulturtanken-rogaland
            - name: kulturtanken.organisations.971045698.username
              valueFrom:
                secretKeyRef:
                  name: kulturtanken-rogaland
                  key: username
            - name: kulturtanken.organisations.971045698.password
              valueFrom:
                secretKeyRef:
                  name: kulturtanken-rogaland
                  key: password
            - name: spring.security.oauth2.client.registration.921693230.client-id
              valueFrom:
                secretKeyRef:
                  key: client-id
                  name: kulturtanken-viken
            - name: spring.security.oauth2.client.registration.921693230.client-secret
              valueFrom:
                secretKeyRef:
                  key: client-secret
                  name: kulturtanken-viken
            - name: kulturtanken.organisations.921693230.username
              valueFrom:
                secretKeyRef:
                  name: kulturtanken-viken
                  key: username
            - name: kulturtanken.organisations.921693230.password
              valueFrom:
                secretKeyRef:
                  name: kulturtanken-viken
                  key: password
            - name: fint.basic.username
              valueFrom:
                secretKeyRef:
                  name: kulturtanken-rogaland
                  key: basic-username
            - name: fint.basic.password
              valueFrom:
                secretKeyRef:
                  name: kulturtanken-rogaland
                  key: basic-password
