apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: kulturtanken
  name: kulturtanken
spec:
  ports:
    - name: "8080"
      port: 8080
  type: LoadBalancer
  selector:
    io.kompose.service: kulturtanken
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kulturtanken
  name: kulturtanken
spec:
  replicas: 1
  minReadySeconds: 30
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      io.kompose.service: kulturtanken
  template:
    metadata:
      labels:
        io.kompose.service: kulturtanken
    spec:
      containers:
        - name: kulturtanken-beta
          image: fintlabs.azurecr.io/kulturtanken:build.3
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /kulturtanken/actuator/health
          resources:
            limits:
              memory: "1.5Gi"
              cpu: "500m"
            requests:
              cpu: "100m"
              memory: "256Mi"
          env:
            - name: TZ
              value: Europe/Oslo
            - name: server.servlet.context-path
              value: "/kulturtanken"
            - name: webclient.handler.timeout.value
              value: "8"
