apiVersion: v1
kind: Service
metadata:
  name: kulturtanken
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    io.kompose.service: kulturtanken
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kulturtanken
  labels:
    io.kompose.service: kulturtanken
spec:
  selector:
    matchLabels:
      io.kompose.service: kulturtanken
  template:
    metadata:
      labels:
        io.kompose.service: kulturtanken
    spec:
      containers:
        - name: kulturtanken-beta
          image: fintlabs.azurecr.io/kulturtanken:resttemplate.10
          resources:
            limits:
              memory: "1.5Gi"
              cpu: "500m"
            requests:
              cpu: "100m"
              memory: "256Mi"
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /tjenester/kulturtanken/actuator/health
          env:
            - name: TZ
              value: Europe/Oslo
            - name: server.servlet.context-path
              value: "/tjenester/kulturtanken"
            - name: fint.oauth.enabled
              value: 'true'
            - name: fint.oauth.client-id
              valueFrom:
                secretKeyRef:
                  key: client-id
                  name: kulturtanken-rogaland
            - name: fint.oauth.client-secret
              valueFrom:
                secretKeyRef:
                  key: client-secret
                  name: kulturtanken-rogaland
            - name: fint.oauth.username
              valueFrom:
                secretKeyRef:
                  name: kulturtanken-rogaland
                  key: username
            - name: fint.oauth.password
              valueFrom:
                secretKeyRef:
                  name: kulturtanken-rogaland
                  key: password
            - name: fint.oauth.access-token-uri
              value: https://idp.felleskomponent.no/nidp/oauth/nam/token
            - name: fint.oauth.scope
              value: fint-client
            - name: spring.security.user.name
              valueFrom:
                secretKeyRef:
                  name: kulturtanken-rogaland
                  key: basic-username
            - name: spring.security.user.password
              valueFrom:
                secretKeyRef:
                  name: kulturtanken-rogaland
                  key: basic-password
