fint:
  oauth:
    enabled: true
    username:
    password:
    client-id:
    client-secret:
    scope:
    access-token-uri:
  endpoints:
    school: "https://beta.felleskomponent.no/utdanning/utdanningsprogram/skole"
    basis-group: "https://beta.felleskomponent.no/utdanning/elev/basisgruppe"
    level: "https://beta.felleskomponent.no/utdanning/utdanningsprogram/arstrinn"
    teaching-group: "https://beta.felleskomponent.no/utdanning/timeplan/undervisningsgruppe"
    subject: "https://beta.felleskomponent.no/utdanning/timeplan/fag"

nsr:
  endpoints:
    unit: "https://data-nsr.udir.no/enhet/{id}"

server:
  servlet:
    context-path: "/tjenester/kulturtanken"

spring:
  security:
    user:
      name:
      password: