fint:
  oauth:
    enabled: true
    username:
    password:
    client-id:
    client-secret:
    access-token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
    scope: fint-client

  endpoints:
    school: https://beta.felleskomponent.no/utdanning/utdanningsprogram/skole
    basis-group: https://beta.felleskomponent.no/utdanning/elev/basisgruppe
    level: https://beta.felleskomponent.no/utdanning/utdanningsprogram/arstrinn
    teaching-group: https://beta.felleskomponent.no/utdanning/timeplan/undervisningsgruppe
    subject: https://beta.felleskomponent.no/utdanning/timeplan/fag

nsr:
  endpoints:
    unit: https://data-nsr.udir.no/enhet/{id}

kulturtanken:
  organisations:
    958381492:
      name: Akershus
      source: nsr
      groups: false
      username:
      password:
    943039046:
      name: Aust-Agder
      source: nsr
      groups: false
      username:
      password:
    964951373:
      name: Buskerud
      source: nsr
      groups: false
      username:
      password:
    964994218:
      name: Finnmark
      source: nsr
      groups: false
      username:
      password:
    942116217:
      name: Hedmark
      source: nsr
      groups: false
      username:
      password:
    938626367:
      name: Hordaland
      source: nsr
      groups: false
      username:
      password:
    944183779:
      name: Møre og Romsdal
      source: nsr
      groups: false
      username:
      password:
    964982953:
      name: Nordland
      source: nsr
      groups: false
      username:
      password:
    961382335:
      name: Oppland
      source: nsr
      groups: false
      username:
      password:
    958935420:
      name: Oslo
      source: nsr
      groups: false
      username:
      password:
    971045698:
      name: Rogaland
      source: fint
      groups: true
      username:
      password:
    941388841:
      name: Sogn og Fjordane
      source: nsr
      groups: false
      username:
      password:
    940192226:
      name: Telemark
      source: nsr
      groups: false
      username:
      password:
    864870732:
      name: Troms
      source: nsr
      groups: false
      username:
      password:
    817920632:
      name: Trøndelag
      source: nsr
      groups: false
      username:
      password:
    960895827:
      name: Vest-Agder
      source: nsr
      groups: false
      username:
      password:
    944025391:
      name: Vestfold
      source: nsr
      groups: false
      username:
      password:
    842952972:
      name: Østfold
      source: nsr
      groups: false
      username:
      password:

server:
  servlet:
    context-path: /tjenester/kulturtanken

spring:
  security:
    user:
      name:
      password: