kulturtanken:
  organisations:
    921707134:
      name: Agder
      organisationnumber: 921707134
      source: nsr
      groups: false
      registration:
        1:
          id:
          username:
          password:
          environment:
    920717152:
      name: Innlandet
      organisationnumber: 920717152
      source: nsr
      groups: false
      registration:
        1:
          id:
          username:
          password:
          environment:
    944183779:
      name: Møre og Romsdal
      organisationnumber: 944183779
      source: nsr
      groups: false
      registration:
        1:
          id:
          username:
          password:
          environment:
    964982953:
      name: Nordland
      organisationnumber: 964982953
      source: nsr
      groups: false
      registration:
        1:
          id:
          username:
          password:
          environment:
    958935420:
      name: Oslo
      organisationnumber: 958935420
      source: nsr
      groups: false
      registration:
        1:
          id:
          username:
          password:
          environment:
    971045698:
      name: Rogaland
      organisationnumber: 971045698
      source: fint
      groups: true
      registration:
        1:
          id:
          username:
          password:
          environment:
    922420866:
      name: Troms og Finnmark
      organisationnumber: 922420866
      source: nsr
      groups: false
      registration:
        1:
          id:
          username:
          password:
          environment:
    817920632:
      name: Trøndelag
      organisationnumber: 817920632
      source: nsr
      groups: false
      registration:
        1:
          id:
          username:
          password:
          environment:
    821227062:
      name: Vestfold og Telemark
      organisationnumber: 821227062
      source: fint
      groups: true
      registration:
        1:
          id:
          username:
          password:
          environment:
        2:
          id:
          username:
          password:
          environment:
    821311632:
      name: Vestland
      organisationnumber: 821311632
      source: nsr
      groups: false
      registration:
        1:
          id:
          username:
          password:
          environment:
    921693230:
      name: Viken
      organisationnumber: 921693230
      source: fint
      groups: true
      registration:
        1:
          id:
          username:
          password:
          environment: