fint:
  oauth:
    enabled: true
    username:
    password:
    client-id:
    client-secret:
    scope:
    access-token-uri:
  base-uri: "https://beta.felleskomponent.no"

nsr:
  endpoints:
    unit: "https://data-nsr.udir.no/enhet/{id}"

server:
  servlet:
    context-path: "/tjenester/kulturtanken"

spring:
  security:
    user:
      name:
      password: