kulturtanken:
  organisations:
    921707134:
      name: Agder
      organisationnumber:
      source:
      groups:
      registration:
        1:
          id:
          username:
          password:
          environment:
        2:
          id:
          username:
          password:
          environment:
    920717152:
      name: Innlandet
      organisationnumber:
      source:
      groups:
      registration:
        1:
          id:
          username:
          password:
          environment:
    944183779:
      name: Møre og Romsdal
      organisationnumber:
      source:
      groups:
      registration:
        1:
          id:
          username:
          password:
          environment:
    964982953:
      name: Nordland
      organisationnumber:
      source:
      groups:
      registration:
        1:
          id:
          username:
          password:
          environment:
    958935420:
      name: Oslo
      organisationnumber:
      source:
      groups:
      registration:
        1:
          id:
          username:
          password:
          environment:
    971045698:
      name: Rogaland
      organisationnumber:
      source:
      groups:
      registration:
        1:
          id:
          username:
          password:
          environment:
    922420866:
      name: Troms og Finnmark
      organisationnumber:
      source:
      groups:
      registration:
        1:
          id:
          username:
          password:
          environment:
    817920632:
      name: Trøndelag
      organisationnumber:
      source:
      groups:
      registration:
        1:
          id:
          username:
          password:
          environment:
    821227062:
      name: Vestfold og Telemark
      organisationnumber:
      source:
      groups:
      registration:
        1:
          id:
          username:
          password:
          environment:
        2:
          id:
          username:
          password:
          environment:
    821311632:
      name: Vestland
      organisationnumber:
      source:
      groups:
      registration:
        1:
          id:
          username:
          password:
          environment:
    921693230:
      name: Viken
      organisationnumber:
      source:
      groups:
      registration:
        1:
          id:
          username:
          password:
          environment: