fint:
  basic:
    username:
    password:

nsr:
  endpoints:
    unit: https://data-nsr.udir.no/enhet/{id}

kulturtanken:
  organisations:
    921707134:
      name: Agder
      source: nsr
      groups: false
      username:
      password:
      environment:
    920717152:
      name: Innlandet
      source: nsr
      groups: false
      username:
      password:
      environment:
    944183779:
      name: Møre og Romsdal
      source: nsr
      groups: false
      username:
      password:
      environment:
    964982953:
      name: Nordland
      source: nsr
      groups: false
      username:
      password:
      environment:
    958935420:
      name: Oslo
      source: nsr
      groups: false
      username:
      password:
      environment:
    971045698:
      name: Rogaland
      source: fint
      groups: true
      username:
      password:
      environment: https://beta.felleskomponent.no
    922420866:
      name: Troms og Finnmark
      source: nsr
      groups: false
      username:
      password:
      environment:
    817920632:
      name: Trøndelag
      source: nsr
      groups: false
      username:
      password:
      environment:
    821227062:
      name: Vestfold og Telemark
      source: nsr
      groups: false
      username:
      password:
      environment:
    821311632:
      name: Vestland
      source: nsr
      groups: false
      username:
      password:
      environment:
    921693230:
      name: Viken
      source: fint
      groups: true
      username:
      password:
      environment: https://api.felleskomponent.no

server:
  servlet:
    context-path: /tjenester/kulturtanken

spring:
  security:
    oauth2:
      client:
        registration:
          971045698:
            client-id:
            client-secret:
            authorization-grant-type: password
            scope: fint-client
            provider: fint
          921693230:
            client-id:
            client-secret:
            authorization-grant-type: password
            scope: fint-client
            provider: fint
        provider:
          fint:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token