apiVersion: apps/v1
kind: Deployment
metadata:
  name: fint-kulturtanken
spec:
  template:
    spec:
      containers:
        - name: kulturtanken
          env:
            - name: kulturtanken.organisations.971045698.organisationnumber
              value: '971045698'
            - name: kulturtanken.organisations.971045698.source
              value: fint
            - name: kulturtanken.organisations.971045698.groups
              value: 'true'
            - name: kulturtanken.organisations.971045698.registration.1.id
              value: 'rogaland'
            - name: kulturtanken.organisations.971045698.registration.1.environment
              value: https://api.felleskomponent.no
            - name: kulturtanken.organisations.971045698.registration.1.username
              valueFrom:
                secretKeyRef:
                  name: kulturtanken-rogaland
                  key: username
            - name: kulturtanken.organisations.971045698.registration.1.password
              valueFrom:
                secretKeyRef:
                  name: kulturtanken-rogaland
                  key: password
            - name: spring.security.oauth2.client.registration.rogaland.client-id
              valueFrom:
                secretKeyRef:
                  key: client-id
                  name: kulturtanken-rogaland
            - name: spring.security.oauth2.client.registration.rogaland.client-secret
              valueFrom:
                secretKeyRef:
                  key: client-secret
                  name: kulturtanken-rogaland
            - name: spring.security.oauth2.client.registration.rogaland.authorization-grant-type
              value: password
            - name: spring.security.oauth2.client.registration.rogaland.scope
              value: fint-client
            - name: spring.security.oauth2.client.registration.rogaland.provider
              value: fint
