apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: kulturtanken-rogaland
spec:
  itemPath: "vaults/aks-api-vault/items/dks-rogfk"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: kulturtanken-oslo
spec:
  itemPath: "vaults/aks-api-vault/items/dks-oslo"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: kulturtanken-mrfk
spec:
  itemPath: "vaults/aks-api-vault/items/dks-mrfk"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: kulturtanken-vtfk
spec:
  itemPath: "vaults/aks-api-vault/items/dks-vtfk"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: kulturtanken-agder
spec:
  itemPath: "vaults/aks-api-vault/items/dks-agderfk"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: kulturtanken-innlandet
spec:
  itemPath: "vaults/aks-api-vault/items/dks-innlandet"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: kulturtanken-viken
spec:
  itemPath: "vaults/aks-api-vault/items/dks-viken"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: kulturtanken-nordland
spec:
  itemPath: "vaults/aks-api-vault/items/dks-nfk"
